---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpuexecutioncap: 50
  pre_create_command: mkdir -p .testcache

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver:
      synced_folders:
        - [".testcache", "/tmp/mule"]
  - name: windows-2012r2
    driver:
      box: kensykora/windows_2012_r2_standard
      synced_folders:
        - [".testcache", "c:/tmp/mule"]

suites:
  - name: default
    run_list:
      - recipe[mule-test::default]
    attributes:
      aws:
        access_key: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        secret: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
